#! /usr/bin/env python3

import parse_iheart_json

import urllib.error
import argparse
import subprocess
import logging
import time

# Something that will cause a player to error out, written to stdout when we
# can't get a real station URL for some reason
BAD_STATION = "no://station/found"

def dump_station_details (station, dumpfunc = print):
	dumpfunc ("station name: %s" % station['name'])
	dumpfunc ("call letters: %s" % station['callLetters'])
	dumpfunc ("location: %s" % station['markets'][0]['city'] + ", " + station['markets'][0]['stateAbbreviation'] + ", " + station['markets'][0]['country'])
	dumpfunc ("description: %s" % station['description'])
	dumpfunc ("broadcast format: %s" % station['format'])

def print_url (station_id):
	station = None
	attempts = 0

	while (attempts < 3):
		try:
			station = parse_iheart_json.station_info (station_id, tls)
			break
		except urllib.error.HTTPError as inst:
			# Attempt to compensate for random HTTP 500 errors
			logging.warning ("http error from iheart server; retrying:")
			logging.warning (inst)
			attempts += 1
			time.sleep (2);
		except RuntimeError as inst:
			logging.error (inst)
			print (BAD_STATION)
			return
	else:
		logging.error ("could not get station URL")
		print (BAD_STATION)
		return

	if (args.verbose):
		try:
			dump_station_details (station, dumpfunc = logging.debug)
		except KeyError:
			logging.warning ("a field is missing; please run with -v and submit a github issue")
			logging.debug ("full dictionary dump:")
			logging.debug (station)

	try:
		station_url = parse_iheart_json.get_station_url (station, tls)
	except KeyError as inst:
		if (str (inst) == 'None'):
			logging.error ("no valid stream for this station (if tls is off, try turning it on)")
			print (BAD_STATION)
			return
		else:
			logging.info ("an unknown stream type is present, please run with -v and submit a github issue")
			logging.info ("KeyError instance: %s", inst)
			logging.debug ("full dictionary dump:")
			logging.debug (station)
			print (BAD_STATION)
			return

	print (station_url)

if (__name__ == '__main__'):

	parser = argparse.ArgumentParser (description="Print the audio stream URL for an iheartradio station")

	# Optional arguments
	parser.add_argument (
		'-v', '--verbose',
		action='count',
		help="Display extra information",
		)
	parser.add_argument (
		'-i', '--info',
		action='store_true',
		help="Instead of printing the stream URL for the station, output some information about it",
		)
	parser.add_argument (
		'-c', '--cleartext',
		action='store_true',
		help="Disable TLS when communicating with iHeartRadio, and do not return a TLS stream URL",
		)

	# The three required arguments; one and only one must be given
	action = parser.add_mutually_exclusive_group(required=True)
	action.add_argument (
		'station_id',
		nargs='?',
		type=int,
		help="The (five-digit?) ID number of the station",
		)	
	action.add_argument (
		'-s', '--search',
		metavar='TERMS',
		help="List station search results for TERMS"
		)
	action.add_argument (
		'-l', '--lucky',
		metavar='TERMS',
		help="\"I\'m feeling lucky\" search for TERMS (print URL for the first result)"
		)

	args = parser.parse_args ()

	if (args.verbose):
		logging.basicConfig (format = "%(levelname)s".lower () + ": %(message)s", level = logging.DEBUG)
	else:
		logging.basicConfig (format = "%(levelname)s: %(message)s", level = logging.INFO)

	tls = not args.cleartext

	if (args.search):
		results = parse_iheart_json.station_search (args.search, tls)

		print ("hits:", results['totalStations'])
		for station in results['stations']:
			if (args.verbose):
				print ("\n-- name:", station['name'], "id:" + str(station['id']))
				print ('\t', "callsign:", station['callLetters'])
				print ('\t', "frequency:", station['frequency'])
				print ('\t', "city:", station['city'])
				print ('\t', "state:", station['state'])
				print ('\t', "description:", station['description'])
				print ('\t', "relevancy score:", station['score'])
			else:
				print (station['name'], '\t', station['description'], "id:" + str(station['id']))
	else:
		# Determine station_id, either by the lucky search or from the
		# commandline
		if (args.lucky):
			results = parse_iheart_json.station_search (args.lucky, tls)

			# iheart will not necessarily decide that one match is
			# "best" for us
			if (results['bestMatch'] is not None):
				station_id = (results['bestMatch']['id'])
			else:
				logging.error ("no stations found for \"I'm feeling lucky\" search")
				print (BAD_STATION)
				exit ()
		else:
			station_id = args.station_id

		# Print info XOR print URL, for the station_id found above
		if (args.info):
			station = None;
			try:
				station = parse_iheart_json.station_info (station_id, tls)
				dump_station_details (station)
			except KeyError:
				logging.error ("information field not found (has the iHeartRadio API changed?) please run with -v and submit a github issue")
				logging.debug ("full dictionary dump:")
				logging.debug (station)
		else:
			print_url (station_id)
